### ISSUE TITLE
[Feature] Bandwidth Limit

### ISSUE THREAD

**Issue by Flupster** [tpill90/steam-lancache-prefill#104]
Some including myself have a weak internet connection and use Lancache as a means to pre-download games so when I decide to actually download them via steam I get blazingly fast speeds

The problem is that downloading the games saturates the internet connections speed which causes massive latency to the point the connection becomes unusable

Adding a launch flag to limit download speed would be handy to limit the speed and allow the connection to be usable

The main problem I foresee is limiting the speed on already cached apps

Example:

`SteamPrefill prefill --rate 5000`

Expectation:

Starts the prefill operation with a limit of 5000KB/s

**Comment by physk** [comment]
Personally, I use Proxmox LXC container to run lancache & the prefills and then set a rate limit on the container network

![image](https://user-images.githubusercontent.com/32438947/188343103-f5758d44-8a35-4a0b-9d07-78cac86bd0f7.png)

Note: if you are running lancache on the same container as the prefill you will have to un-limit it again when you want to download the game through the cache, or it will be limited to what you set

Hope this works as a temporary work around.

**Comment by tpill90** [comment]
Hi @Flupster,

I appreciate you taking the time to create an issue for this request.  Unfortunately with the way that SteamPrefill is designed it isn't possible to implement a way to throttle it's download speed.  At least not with a very significant complete overhaul of how downloads are handled.

However, despite this there are other methods of achieving what you are looking for.  I've documented some of these methods in the project readme, which can be found here : [New readme section](https://github.com/tpill90/steam-lancache-prefill#how-can-i-limit-download-speeds)

I would appreciate any feedback you may have on the documentation, so that I can make it as helpful as possible for others who might have the same idea.

I'm closing this for now, but if you have any feedback please feel free to re-open and leave the feedback here.
