### ISSUE TITLE
Allow use of multiple accounts for prefilling

### ISSUE THREAD

**Issue by GotenXiao** [tpill90/steam-lancache-prefill#113]
An operator may want to cache a set of titles to prepare for a network/event, but not own all of them on one account; barring use of tools like Steam Family Sharing (which have limitations if the accounts are in use), there's currently no convenient way to allow multiple accounts to be used to download a desired list of app IDs.

[lancache-autofill](https://github.com/zeropingheroes/lancache-autofill) allowed authorising multiple accounts and then using the relevant accounts with ownership of a title to perform the download.

**Comment by frozenjava** [comment]
This feature would be really useful since my girlfriend and I have separate steam libraries that'd we'd both like cached. For now I just have duplicate configs and change it out for whichever account I'm wanting to use at the time

**Comment by tpill90** [comment]
While this would certainly be a great feature to have, at this time I don't think that I'm going to end up implementing it.  The changes to make this happen are going to be fairly significant, and at this point SteamPrefill is completely stable and bug free and I would prefer to not risk introducing new issues.  Additionally, since SteamPrefill is self-contained the workaround for multiple accounts is very simple:  create one instance of SteamPrefill for each account.  I've documented this on the project docs at [Can I use more than one steam account at the same time?](https://tpill90.github.io/steam-lancache-prefill/faq/#can-i-use-more-than-one-steam-account-at-the-same-time)
