### ISSUE TITLE
Error while downloading manifests

### ISSUE THREAD

**Issue by kp2341** [tpill90/steam-lancache-prefill#175]
Unknown error while downloading manifests for Dota 2, Life is Strange, Metro 2033 Redux and Metro Last Light Redux.

**Comment by kp2341** [comment]
Hi,

Try following this GitHub article it appears to have worked for me:

https://github.com/lancachenet/monolithic/issues/80

**Comment by tpill90** [comment]
> 

I agree with you @billthecatt that a better error message would be helpful here.  Unfortunately, SteamPrefill is a client and has no real insight into whats going on with the upstream Lancache server.  There can be any number of reasons that the manifest download might fail because of the Lancache server, however they all generally get lumped into a "unspecified" 504 server error.

**Comment by tpill90** [comment]
I'm going to close this issue for now, since the issue seems to be resolved for @kp2341 .

@billthecatt if the solution that @kp2341 posted doesn't resolve the issue for you, please feel free to open a new issue.
