### ISSUE TITLE
Feature request: Please add notifications about prefilling

### ISSUE THREAD

**Issue by SuberSeb** [tpill90/steam-lancache-prefill#259]
Hello.

In my opinion, it would be useful to have notifications about the beginning of the download and the end of the download of a particular game or about an error. I want to suggest implement that notifications using Gotify for example. Gotify is self hosted and have simple api https://gotify.net/api-docs

**Comment by tpill90** [comment]
I'm not sure I entirely understand what the benefit here would be. 

The application always starts the downloads when you run it, so that would be a given.  And it finishes downloading when it terminates, which the operating system would be able to detect. 

Could you give me more background on how this would be useful in your scenario?

**Comment by SuberSeb** [comment]
I've installed this app on my server via Docker and it runs by cron every day. So the only way to check if there was an error, game was downloaded, not downloaded, updated or something else was happened is to check logs manually. I suggest to use push notifications for that kind of events so user will know immediately that something happened. I think this would be useful.

**Comment by tpill90** [comment]
Correct me if I'm wrong, but wouldn't it be possible to add a `grep` onto the cron jobs that could notify you based on whether or not there was the text `failed` in the job?

**Comment by tpill90** [comment]
One more thing I'm curious about,  would you happen to be running SteamPrefill on Unraid via Ich777's container?

**Comment by ich777** [comment]
@SuberSeb du you run my container that I've made for Unraid?



> I want to suggest implement that notifications using Gotify for example. Gotify is self hosted and have simple api https://gotify.net/api-docs

Implementing only one notification service is pretty bad from my opinion, I would rather implement something like [Apprise](https://github.com/caronc/apprise) because you can nearly use any notification service you want, including Gotify.

However can you please describe about what errors you want to be notified about, or what does exactly fail on your end?
