### ISSUE TITLE
Stuck downloads

### ISSUE THREAD

**Issue by reg98643t** [tpill90/steam-lancache-prefill#289]
After a while downloads seem to just stop, seems to be typically at 99% complete. Appears to be a manifests issue?

Previously discussed with @tpill90 on the discord.

Discord: Doctor Dank

**Comment by reg98643t** [comment]
Don't know if this is "fixed" but the behavior changed positively after changing docker from macvlan to ipvlan in unraid.

Instead of being stuck at 99% forever, it will now just fail as normal, retry a few times, and if it can't get it will continue to the next one, which is better if still not ideal.

**Comment by tpill90** [comment]
The change from macvlan is interesting to know since it's not the first time that someone has mentioned that it was causing issues for them. Might be a thing to keep an eye out for in the future. 

It sounds like this is technically "fixed" since the correct behavior of failing and continuing is now happening.  Going to close this for now
