### ISSUE TITLE
Fixed credentials + maFile support 

### ISSUE THREAD

**Issue by asn007** [tpill90/steam-lancache-prefill#303]
**Describe the bug**
Not really a bug, more so a feature request.

Can you add support for storing login, password and working with maFile to generate steam 2fa code on the fly?

**Additional Details**
We're running a LAN gaming center with lancache installed to speed up game updates on our machines. We have a dedicated steam account for prefilling lancache
Re-logging once every few months, even though months, is rather inconvenient. I'd gladly appreciate if you add support for storing username / password pair, possibly encrypted, along with maFile on a machine, so steam-lancache-prefill could re-login with 2FA automatically in case authentication token expires

**Comment by tpill90** [comment]
Hi @asn007,

How frequently are you getting logged out of SteamPrefill?  With the recent changes made to the authentication methods there really shouldn't be any more logouts, at least not for 6 months.

Could you give me some more info on what maFile is?  A quick google doesn't bring up any concrete results for me.

**Comment by asn007** [comment]
@tpill90 so far it's not really frequent, yeah. Haven't had a logout since the latest update, but if it's possible to eliminate the re-login step I'd gladly do it, since the business is already heavy on the operational side of things as is, and having one less thing to keep track of is good. maFile is a Steam Mobile Authenticator file mobile Steam app uses to keep 2FA secrets in.

It's normally heavily used in Steam trading bots, since there's a need to generate a lot of 2FA codes quickly for different accounts

As an example you can take a look at Steam Desktop Authenticator and SteamAuth library (namely, this file: https://github.com/geel9/SteamAuth/blob/master/SteamAuth/SteamGuardAccount.cs)

**Comment by tpill90** [comment]
I don't think I would like to implement any way of storing the username/password myself. That opens this software up to all sorts of security issues, and I don't want to risk that with people's accounts that have real money invested in them. 

The real issue here is having the login session expire when it shouldn't be expiring. To the best of my knowledge the current login should be good for six months without logging in. It should also be refreshed on every login. 

I would suggest that you try to keep track of how frequently you're getting logged out, so that I can try to find the root cause of it. 

I'm going to leave this issue open so that we can track that.

**Comment by tpill90** [comment]
Since I haven't heard anything back in the last few months, I'm going to assume that there haven't been any further logouts.

I'm going to close this for now, but please feel free to reopen if the logouts start happening again.
