### ISSUE TITLE
[FEATURE REQUEST] Webhooks (Discord etc)

### ISSUE THREAD

**Issue by NPetersenDK** [tpill90/steam-lancache-prefill#327]
Hi there,

Thanks for this nifty software, its really nice. 

This is very standalone and thats a good thing, but that also means it is set and forget in some way. Would it be possible to make support for Discord Webhooks in some kind of configuration aspect?

That way it could post to Discord if:
- It downloaded and it went good.
- Any errors and why

At the place where I host this, we use Discord webhooks to many things.

Reference: https://discord.com/developers/docs/resources/webhook#execute-webhook

EDIT: This issue might have been better placed in [lancache-prefill-common](https://github.com/tpill90/lancache-prefill-common), that i first see now, sorry.

Thanks.

**Comment by tpill90** [comment]
Hi Nikolaj,

I appreciate you taking the time to open up an issue for this suggestion.  I've been giving some thought to this, and it totally makes sense from a "visibility" standpoint, since the app will usually end up being ran in the background.

My one concern with a feature like this is that it would invite adding other additional notification methods like email, SMS, etc.  And this would quickly add bloat to the app for something that is not necessarily in scope for it.  I think that the best way to achieve this would be to write a quick shell script that wraps running SteamPrefill and sending the notification, and configure it to run as a scheduled job like so : [Scheduled Job Setup](https://tpill90.github.io/steam-lancache-prefill/install-guides/Scheduled-Job/)

I'd also be more than happy to help out with throwing a script together if you need a hand.  This might even be something that would be at home in the project wiki, where it could possibly help someone else in the future.

**Comment by tpill90** [comment]
Closing as this won't be implemented.
