### ISSUE TITLE
Unable to prefill Steam games

### ISSUE THREAD

**Issue by MaverickX009** [tpill90/steam-lancache-prefill#328]
**Describe the bug**
Recently everytime I attempt to prefill my lancache with Steamgames, I continue to get errors and it basically times out from attempting to download the games. When I first started this, everything worked as designed, but not sure what is causing this now, as there has not been any big change on my network. The only thing I can think of is possibly Unraid being updated to 6.12.4 as it had some big changes to the cache settings.

**Additional Details**
 -Running this on Unraid 6.12.4 in Docker with Lancache Monolithic, Lancache DNS, and Lancache-Prefill
 - Discord Username: MaverickX009
 - Region : US East Coast

**Screenshots**
Including a couple screenshots.

<img width="580" alt="image" src="https://github.com/tpill90/steam-lancache-prefill/assets/146785238/ec97c195-7df4-45a2-a170-2a15170a476f">

<img width="500" alt="image" src="https://github.com/tpill90/steam-lancache-prefill/assets/146785238/952d8380-fb98-491d-9678-6dac028c5bb6">

<img width="505" alt="image" src="https://github.com/tpill90/steam-lancache-prefill/assets/146785238/8bf5891a-e3ce-4817-bc23-91d69f1db73b">

**Comment by tpill90** [comment]
@MaverickX009 Could you please attach your `app.log` to this issue so I can take a look at it?

**Comment by tpill90** [comment]
[app.log](https://github.com/tpill90/steam-lancache-prefill/files/12885462/app.log)
<img width="763" alt="image" src="https://github.com/tpill90/steam-lancache-prefill/assets/766513/c2c4dede-4452-40fc-b4e4-78c34dae2705">

**Comment by preppie22** [comment]
Have the same problem as described in this issue. However, in my case it stays stuck on "Fetching depot manifests...".

This is when running the tool on a machine running Ubuntu Server 22.04 with a static internal IP (public IP is dynamic). Lancache has been setup on this Ubuntu machine using a Docker image. It has been tested and working when games are downloaded from another machine running Steam on the same local network. SteamPrefill has been installed directly without Docker by downloading and using the update.sh file. Unlike MaverickX, I have a single LAN network and DHCP is handled by a router. Do note that my internet is sometimes unstable and is usually slow. Which is why I'm using Lancache and SteamPrefill to download game updates at night.

I've also tested this on a Windows machine running on the local network. When selecting 5 games to test with, the first game downloads perfectly while the next one gets stuck on "Fetching depot manifests...". I let this run for about 3 hours but nothing changed. Previously, I'd also tried this on the Ubuntu Server machine and left it running for 24 hours and it remained stuck as well.


![Screenshot 2023-10-30 203400](https://github.com/tpill90/steam-lancache-prefill/assets/16285872/684c510a-4753-49ca-8f5a-0f162dcdd73b)

Attaching the [app.log](https://github.com/tpill90/steam-lancache-prefill/files/13211754/app.log) file from the Windows test run here for reference.

**Comment by preppie22** [comment]
Hey, I wanted to let you know that the issue seems to have fixed itself. What changed was that when I did the test, my network was experiencing some packet loss. It's been restored to normal today and SteamPrefill is working correctly.

This is still not intended behavior because networks may experience packet loss on occasion, so the program should be able to mitigate that... The problem appears to be that the program is hanging if it doesn't receive a response in a few seconds. Maybe a timeout of some sort would help?

**Comment by tpill90** [comment]
I've added an extra timeout to where I think the issue might be occurring.  I'll include the change in the next release

**Comment by tpill90** [comment]
Released timeout fix in [v2.3.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v2.3.0)
