### ISSUE TITLE
[Feature Request] Add Steam software to prefill

### ISSUE THREAD

**Issue by c11umw** [tpill90/steam-lancache-prefill#362]
**Describe the bug**
Games are available to download, but not software
e.g. Virtual Desktop, Facerig

**Additional Details**
Dedicated Proxmox LXC for Lancache and prefill.
Ubuntu 23.10 Docker  + local disk

**Screenshots**
Missing example: FaceRig
![image](https://github.com/tpill90/steam-lancache-prefill/assets/48920056/47554028-6283-45f0-a467-2a21afd38935)

**Comment by tpill90** [comment]
Hi @c11umw. Could you tell me more about your use case? Is this kind of software something you find is getting installed frequently across clients?

**Comment by c11umw** [comment]
Some do. For example Virtual Desktop is one I use that updated regularly.

I don't use the editing software that's on Steam (Vegas Pro?), but I'm sure that would also get frequent updates and be fairly substantial in size. 1.5Gb according to [a google search.](https://letmegooglethat.com/?q=how+much+diskspace+for+VEGAS+Pro+18+Edit+Steam+Edition)

![image](https://github.com/tpill90/steam-lancache-prefill/assets/48920056/6665f1d7-37a5-48f2-aefe-0e60628e812b)

**Comment by tpill90** [comment]
Sorry for another late reply, one more question.  Do you have a relatively slow internet connection?

**Comment by c11umw** [comment]
Nope. Internet here is speedy.

**Comment by tpill90** [comment]
While I understand that this would certainly be helpful in some use cases, this isn't something that I'm going to implement.  The primary design of SteamPrefill is to bulk download games prior to a LAN party,  so its entirely game focused.  Since downloading games is what most users are going to be using it for, I don't want to clutter `select-apps` with software and other tools (which there can be a lot of in some cases).

The change to enable this is very easy to make, its only a change to the filtering logic.  I could point you to what you need to change, as well as the docs on how to compile this project, if you would be interesting in running your own customized version of SteamPrefill.
