### ISSUE TITLE
[Feature Request] Prefill recently played games from users

### ISSUE THREAD

**Issue by spyfly** [tpill90/steam-lancache-prefill#37]
It would be great to have an option to automatically prefill recently played games from users on your network. This could be done using the corresponding [SteamAPI Endpoint](https://partner.steamgames.com/doc/webapi/IPlayerService#GetRecentlyPlayedGames) and by providing a list of SteamIDs to the program.

Alternatively the recently played tab on Steam could be utilized.

**Comment by tpill90** [comment]
### Implementation tasks

- [ ] Add a flag to the `prefill` command to specify that recently played games should be prefilled
- [ ] Add new flag to list of flags for `prefill` in the readme
- [ ] Add a new section to the readme, detailing how some of the various flags can be used.

**Comment by tpill90** [comment]
Added a new flag `--recent` that will add all recently played games to the download queue.
![image](https://user-images.githubusercontent.com/766513/1867939
[SteamPrefill-1.3.2-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9428995/SteamPrefill-1.3.2-linux-x64.zip)
[SteamPrefill-1.3.2-osx-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9428997/SteamPrefill-1.3.2-osx-x64.zip)
[SteamPrefill-1.3.2-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9428998/SteamPrefill-1.3.2-win-x64.zip)
[SteamPrefill-1.3.2-linux-arm64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9428999/SteamPrefill-1.3.2-linux-arm64.zip)
20-0f210fa3-9960-4b20-9852-d45e51138a35.png)

**Comment by spyfly** [comment]
I think it would be great if you could provide a list of SteamIDs for which the recently played games should be prefilled.

In my example, I am running the prefill-service on an alt account, which receives the games via family sharing, so no actual gaming is taking place on the prefill-account.

**Comment by tpill90** [comment]
> I think it would be great if you could provide a list of SteamIDs for which the recently played games should be prefilled.
> 
> In my example, I am running the prefill-service on an alt account, which receives the games via family sharing, so no actual gaming is taking place on the prefill-account.

This makes sense to me, and could possibly be something I could implement.  However, with the way that SteamPrefill is currently architected, it won't be easy to add this.

I can still consider adding this feature, but I think that this might be outside of the scope of the original request, which has been satisfied.

Would you please split this request out into its own issue?  So that I can accurately keep track of this feature request, while being able to close out the original?

**Comment by spyfly** [comment]
> I can still consider adding this feature, but I think that this might be outside of the scope of the original request, which has been satisfied.
This is the original request, just spelled out differently

**Comment by tpill90** [comment]
I looked more into being able to prefill by recently played, when using family sharing with another user.  To the best of my knowledge, there doesn't seem to be a way to tell what account the games are coming from, at least with the information that SteamPrefill is already pulling.  The way that it currently knows which games are available to prefill is by looking at the current list of account licenses.  When a family share is enabled, those licenses show up temporarily as part of the the current users account, seemingly as though they are owned by the current user.

Since there doesn't seem to be an easy way to implement this, I'm going to close this issue for now.

**Comment by spyfly** [comment]
I think the proper approach would be providing a list of SteamID64's and then getting the recently played games via the aforementioned Steam API Endpoint.
