### ISSUE TITLE
Feature request: Search for app in applist

### ISSUE THREAD

**Issue by rwesterflan** [tpill90/steam-lancache-prefill#9]
Having more than 500 items in my list, it'd be great to jump to an item (and be able to select items from there)

**Comment by tpill90** [comment]
Possible implementation options

- Typing a single letter will skip to that section of games starting with that letter
- A fuzzy search that allows you to enter a subset of a string, to find all games that match that subset.  E.g. "Fantasy" will bring up "Final Fantasy XV"

**Comment by tpill90** [comment]
A fuzzy search has been implemented in `select-apps-beta`, and will be eventually switched over to replace the existing `select-apps` command.
![image](https://user-images.githubusercontent.com/766513/186438053-369b04d4-6de7-4724-b6ef-7f0aa53c32d0.png)

Closing this since the search has been implemented.
